### PR TITLE
Main feature

### PR DESCRIPTION
**Pull request by certilremy**

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# UNDER REVIEW BY TOLULOPE OLUSAKIN(TSE)
Hello @certilremy, you have done great job and you are almost ready to merge :+1:. Please look into the following and request a re-review.

#### Responsiveness
Your project looks great on desktop,  however, when moving onto smaller screens, the UI breaks. Please take a close look at section specific `paddings`, `margins` and `widths` as they relate to different screen sizes.

#### Navigation
Please take a look at the navigation bar on the original page thoroughly and compare with yours, it breaks a little on mobile.

### Summary
You have major changes to make as regards responsiveness, the padding on most of your sections is too much, a lot of elements are wrongly sized and aligned. Also, take not of how each section adjusts based on what the screen size is and make appropriate changes. You've shown great promise overall and I am positive your project will shine in the end :smile:. See you at the top! :rocket: 

If you think I missed something, or you need some help or you just want to chat, please feel free to message me on [Twitter](https://oluwadamlareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin) and I will be sure to respond!

**Comment by certilremy** [comment]
> # UNDER REVIEW BY TOLULOPE OLUSAKIN(TSE)

I've been waiting for 67 minutes still no update from you.

**Comment by nikasulo** [comment]
Hello @certilremy, please check at break time. No TSE duties are allowed during work hours. Thank you for understanding :100:

**Comment by nikasulo** [comment]
In the meantime, carry on with your next project or something from the professional curriculum

**Comment by certilremy** [comment]
I don't Understand why it's taking so long . Almost 3 hours.

**Comment by certilremy** [comment]
> In the meantime, carry on with your next project or something from the professional curriculum

3 hours this is unfair ! If you're not available to review it why you comment that it's under review from you?   You can just ignore it and and other can review it ?

**Comment by nikasulo** [comment]
Apologies @certilremy, I understand how you feel, however, code reviews cannot be done during regular working hours, that's why student success tells students to allow up to 24 hours after a TSE has claimed the review to receive feedback. I understand you want to keep building and working, however, I am just another student like you enrolled in the program and I require some time to perform reviews so I can give great feedback and not rush over it. Please take this into account and try to understand.

Many Thanks,
All the best in your projects :smile:,
Tolulope Olusakin

**Comment by certilremy** [comment]
> Apologies @certilremy, I understand how you feel, however, code reviews cannot be done during regular working hours, that's why student success tells students to allow up to 24 hours after a TSE has claimed the review to receive feedback. I understand you want to keep building and working, however, I am just another student like you enrolled in the program and I require some time to perform reviews so I can give great feedback and not rush over it. Please take this into account and try to understand.
> 
> Many Thanks,
> All the best in your projects 😄,
> Tolulope Olusakin

I din'd know about this new rule, They didn't send it to me, If there's a change to the program we all need to know for miss-understood. They should email us all about it.

**Comment by nikasulo** [comment]
@certilremy, it's always been a rule, checkout the zendesk for more information on code reviews. Microverse continues to do it's best as regards informing us all but whenever you can, they are open to kind suggestions and recommendations :+1:.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hello @certilremy, great work!
I commend you on your efforts to implement the changes I requested earlier, however, your navigation is still buggy and your page doesn't respond well at 1600px and below, at least not in comparison to the original site.

Please refer to my previous comments and make appropriate changes. Pay attention to the navigation bar, and it's size as well as all the sections from 'In the magazine' and below!

**Comment by certilremy** [comment]
> # Hello @certilremy, great work!
> I commend you on your efforts to implement the changes I requested earlier, however, your navigation is still buggy and your page doesn't respond well at 1600px and below, at least not in comparison to the original site.
> 
> Please refer to my previous comments and make appropriate changes. Pay attention to the navigation bar, and it's size as well as all the sections from 'In the magazine' and below!

Screenshot from  939px.
[https://drive.google.com/file/d/1QISIrxKcgEmml59QifPxi476GFC7GesM/view?usp=sharing](url)

Screenshot from  600px .
[https://drive.google.com/file/d/1TO3egCrnrVhKwpq8ovddeA36Pb9rx_0D/view?usp=sharing](url)

Screenshot from  340px and below.
[https://drive.google.com/file/d/1pyK-GYInybs1PSaXOSGuLSaUN3nwjryc/view?usp=sharing](url)

Please can you send me screenshot so i can see exactly how it's look on your side?

**Pull request merged**
